service: psimplify-b
# app and org for use with dashboard.serverless.com
app: psimplify-b-app
org: fedebaez

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ${file(./variables.yml):region}
  role: ${file(./variables.yml):lambdarole}
  versionFunctions: false
  tags:
    project: Psimplify
  httpApi:
    authorizers:
      serviceAuthorizer: ${file(./variables.yml):cognitouserpool}
  environment:
    AWS_REGION: ${file(./variables.yml):region}

functions:
  users:
    handler: src/adapters/api/users
    events:
      - cognitoUserPool:
        pool: Psimplify
        trigger: PostConfirmation
        existing: true
  user:
    handler: src/adapters/api/users/id
    events:
      - httpApi:
        path: users/{id}
        method: get
        authorizer: serviceAuthorizer

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
