service: psimplify-b
# app and org for use with dashboard.serverless.com
app: psimplify-b-app
org: fedebaez

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-central-1
  role: ${file(./variables.yml):lambdarole}
  versionFunctions: false
  tags:
    project: Psimplify
    resource: users
  environment:
    TABLE_NAME: users

functions:
  register:
    handler: user.register
    events:
      - http:
          path: users
          method: post
  getUserById:
    handler: user.getById
    events:
      - http:
          path: users/{id}
          method: get

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
